name: CMake

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'rust/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'rust/**'
  schedule:
    - cron: '17 17 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        preset: ["Release", "Debug"]

    steps:
    - uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: cpp

    - name: Configure CMake
      run: cmake --preset ${{matrix.preset}}

    - name: build
      run: cmake --build --preset ${{matrix.preset}}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake --preset Windows
  
      - name: build
        run: cmake --build --preset Windows
